/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Role.COManagerRole;
import Business.Worker.Worker;
import Business.CommunityOutreach.CommunityOutreach;
import Business.CommunityOutreach.CommunityOutreachDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;

import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.DonorRole.DonorProfilePanel;

/**
 *
 *@author reetikabhanushali
 */
public class AddCOPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CommunityOutreachDirectory ngod;
    UserAccountDirectory uad;

    public AddCOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();

//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if (ecosystem.getcoDir() == null) {
            ecosystem.setNgoDir(new CommunityOutreachDirectory(ecosystem.getUserAccountDirectory()));
        }

        setBG();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddNonGovtOrgTitle = new javax.swing.JLabel();
        lblCOname = new javax.swing.JLabel();
        txtCOname = new javax.swing.JTextField();
        lblCOPhno = new javax.swing.JLabel();
        txtCOPhone = new javax.swing.JTextField();
        lblCOAdd = new javax.swing.JLabel();
        txtCOAdd = new javax.swing.JTextField();
        lblCOCity = new javax.swing.JLabel();
        txtCOCity = new javax.swing.JTextField();
        lblCOState = new javax.swing.JLabel();
        txtCOState = new javax.swing.JTextField();
        lblCOZip = new javax.swing.JLabel();
        txtCOZip = new javax.swing.JTextField();
        lblCOAgent = new javax.swing.JLabel();
        txtCOAgent = new javax.swing.JTextField();
        lblCOAgentuname = new javax.swing.JLabel();
        txtCOAgentuname = new javax.swing.JTextField();
        lblCOpwd = new javax.swing.JLabel();
        txtCOpwd = new javax.swing.JTextField();
        lblCOpwd1 = new javax.swing.JLabel();
        txtCOpwd1 = new javax.swing.JTextField();
        btnCOSubmit = new javax.swing.JButton();
        lblCOid = new javax.swing.JLabel();
        txtCOid = new javax.swing.JTextField();
        lblNonGovtOrgid2 = new javax.swing.JLabel();
        lblNonGovtOrgname1 = new javax.swing.JLabel();
        lblNonGovtOrgPhone1 = new javax.swing.JLabel();
        lblNonGovtOrgZip1 = new javax.swing.JLabel();
        lblNonGovtOrgAdmin1 = new javax.swing.JLabel();
        lblNonGovtOrgpwd2 = new javax.swing.JLabel();
        btnCOCancel = new javax.swing.JButton();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddNonGovtOrgTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddNonGovtOrgTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblAddNonGovtOrgTitle.setText("Add Community Outreach");
        add(lblAddNonGovtOrgTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        lblCOname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOname.setText("CO Name:");
        add(lblCOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        txtCOname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOnameFocusLost(evt);
            }
        });
        add(txtCOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 137, -1));

        lblCOPhno.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOPhno.setText("CO Phone Number:");
        add(lblCOPhno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        txtCOPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOPhoneFocusLost(evt);
            }
        });
        add(txtCOPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 137, -1));

        lblCOAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOAdd.setText("CO Address:");
        add(lblCOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        txtCOAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOAddActionPerformed(evt);
            }
        });
        add(txtCOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 137, -1));

        lblCOCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOCity.setText("City:");
        add(lblCOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        txtCOCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtCOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 137, -1));

        lblCOState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOState.setText("State:");
        add(lblCOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 20));

        txtCOState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOState.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtCOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 137, -1));

        lblCOZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOZip.setText("Zip:");
        add(lblCOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        txtCOZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOZipFocusLost(evt);
            }
        });
        add(txtCOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 137, -1));

        lblCOAgent.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOAgent.setText("CO Agent Name:");
        add(lblCOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 20));

        txtCOAgent.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOAgentFocusLost(evt);
            }
        });
        add(txtCOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 137, -1));

        lblCOAgentuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOAgentuname.setText("CO Agent Username:");
        add(lblCOAgentuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        txtCOAgentuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOAgentuname.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtCOAgentuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 137, -1));

        lblCOpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOpwd.setText("Password:");
        add(lblCOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        txtCOpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOpwdActionPerformed(evt);
            }
        });
        add(txtCOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 137, -1));

        lblCOpwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOpwd1.setText("Confirm Password:");
        add(lblCOpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        txtCOpwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOpwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOpwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOpwd1FocusLost(evt);
            }
        });
        add(txtCOpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 137, -1));

        btnCOSubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCOSubmit.setText("Submit");
        btnCOSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOSubmitActionPerformed(evt);
            }
        });
        add(btnCOSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        lblCOid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOid.setText("CO ID:");
        add(lblCOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtCOid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOidFocusLost(evt);
            }
        });
        txtCOid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCOidKeyReleased(evt);
            }
        });
        add(txtCOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 134, -1));

        lblNonGovtOrgid2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        lblNonGovtOrgname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 0, 0));

        lblNonGovtOrgPhone1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 0, 0));

        lblNonGovtOrgZip1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, 0));

        lblNonGovtOrgAdmin1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 0, 0));

        lblNonGovtOrgpwd2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblNonGovtOrgpwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 0, 0));

        btnCOCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCOCancel.setText("Cancel");
        btnCOCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOCancelActionPerformed(evt);
            }
        });
        add(btnCOCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1430, 710));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void txtCOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOnameFocusLost
        // TODO add your handling code here:
        if (!(txtCOname.getText().matches("^[a-zA-Z]*$"))) {
            lblNonGovtOrgname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblNonGovtOrgname1.setText("");
        }
    }//GEN-LAST:event_txtCOnameFocusLost

    private void txtCOPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOPhoneFocusLost
        // TODO add your handling code here:
        if (!(txtCOPhone.getText().matches("^[0-9]*$")) || !(txtCOPhone.getText().length() == 10)) {
            lblNonGovtOrgPhone1.setText("Please enter a valid phone number");
            //  lblNGOPhno1.setForeground(Color.red);
        } else {
            lblNonGovtOrgPhone1.setText("");

        }
    }//GEN-LAST:event_txtCOPhoneFocusLost

    private void txtCOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOZipFocusLost
        // TODO add your handling code here:
        if ((txtCOZip.getText().matches("^[a-zA-Z]*$"))) {
            lblNonGovtOrgZip1.setText("Invalid input. Please enter only numbers");

        } else {
            lblNonGovtOrgZip1.setText("");
        }
    }//GEN-LAST:event_txtCOZipFocusLost

    private void txtCOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOAgentFocusLost
        // TODO add your handling code here:
        if (!(txtCOAgent.getText().matches("^[a-zA-Z]*$"))) {
            lblNonGovtOrgAdmin1.setText("Invalid input. Please enter only alphabets.");
        } else {
            lblNonGovtOrgAdmin1.setText("");
        }
    }//GEN-LAST:event_txtCOAgentFocusLost

    private void txtCOpwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOpwd1FocusLost
        // TODO add your handling code here:
//        if(!(txtNGOpwd.getText().equals(txtNGOcopwd1.getText()))){
//            lblNGOpwd2.setText("Password Mismatch. Please verify the password entered.");
//        }
//        else{
//            lblNGOpwd2.setText("");
//        }
    }//GEN-LAST:event_txtCOpwd1FocusLost

    public boolean isValid(String test, String regex) {
//        String regex = "^[A-Za-z0-9]+";
        Pattern p = Pattern.compile(regex);

        if (test == null) {
            return false;
        }

        Matcher m = p.matcher(test);

        return m.matches();
    }

    private void btnCOSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOSubmitActionPerformed
        // TODO add your handling code here:

        if (!nullCheck()) {
            if (chkpwd()) {

                String ngoid = txtCOid.getText();
                String ngoName = txtCOname.getText();
                String phone = txtCOPhone.getText();

                String ngoCity = txtCOCity.getText();
                String ngoState = txtCOState.getText();
                String ngoZip = txtCOZip.getText();
                String ngoAgent = txtCOAgent.getText();
                String ngoUser = txtCOAgentuname.getText();
                String ngoPswd = txtCOpwd.getText();
                if (!isValid(ngoid, "^[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid ID");
                    return;
                }
                if (!isValid(ngoName, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid name");
                    return;
                }
                if (!isValid(phone, "[+]?[0-9]{10,13}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid phone number");
                    return;
                }
                if (!isValid(ngoCity, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid city");
                    return;
                }
                if (!isValid(ngoState, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){2,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid state");
                    return;
                }
                if (!isValid(ngoZip, "^[0-9]{5}(?:-[0-9]{4})?$")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid zip");
                    return;
                }
                if (!isValid(ngoAgent, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid name");
                    return;
                }
                if (!isValid(ngoUser, "^[a-zA-Z0-9._-]{6,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid username of atleast 6 characters");
                    return;
                }
                if (!isValid(ngoPswd, "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password of atleast 8 characters in length. It must contain a number, a specicial character, a lowercase and an uppercase character.");
                    return;
                }

                UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
                Worker employee = new Worker();
                employee.setName(txtCOAgent.getText());
                String role = "NGOAgent";
                CommunityOutreach ngo = new CommunityOutreach();
                ngo.setCOId("ngo" + txtCOid.getText());
                ngo.setCOName(txtCOname.getText());
                ngo.setCOPhone(txtCOPhone.getText());
                ngo.setCOAddress(txtCOAdd.getText());
                ngo.setCOCity(txtCOCity.getText());
                ngo.setCOState(txtCOState.getText());
                ngo.setCOZipcode(txtCOZip.getText());
                ngo.setCOAgent(txtCOAgent.getText());
                UserAccount nogAccount = new UserAccount();
                nogAccount.setUsername(txtCOAgentuname.getText());
                nogAccount.setPassword(txtCOpwd.getText());
                // uaList.createUserAccount(txtFCAuname.getText(), txtFCApwd.getText(), employee, new FCAdminRole());
                //                ua = usersList.getUserAccount(txtUserName.getText());

                nogAccount.setRole(new COManagerRole());
                nogAccount.setEmployee(employee);
                uad = ecosystem.getUserAccountDirectory();
                uad.createUserAccount(txtCOAgentuname.getText(), txtCOpwd.getText(), employee, new COManagerRole());
                ecosystem.setUserAccountDirectory(uad);
                ngo.setCOAccount(nogAccount);
                ngod = ecosystem.getcoDir();
                ngod.addNewNGO(ngo);
                ecosystem.setNgoDir(ngod);
                Integer ngoCnt = ecosystem.getcoCnt();
                ecosystem.setcoCnt(ngoCnt + 1);
                JOptionPane.showMessageDialog(this, "Community Outreach added successfully!");
                clearfields();
            } else {
                JOptionPane.showMessageDialog(this, "Password Mismatch. Please verify the password entered.");
                txtCOpwd1.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnCOSubmitActionPerformed

    private void txtCOidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOidFocusLost
        // TODO add your handling code here:
        if ((txtCOid.getText().matches("^[a-zA-Z]*$"))) {
            lblNonGovtOrgid2.setText("Invalid input. Please enter only numbers");
        } else {
            lblNonGovtOrgid2.setText("");
        }
    }//GEN-LAST:event_txtCOidFocusLost

    private void txtCOidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOidKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCOidKeyReleased

    private void txtCOAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOAddActionPerformed

    private void btnCOCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOCancelActionPerformed
        // TODO add your handling code here:
        clearfields();
    }//GEN-LAST:event_btnCOCancelActionPerformed

    private void txtCOpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOpwdActionPerformed
        if (!Business.Validations.ValidateInputs.isPasswordValid(txtCOpwd.getText())) {
            JOptionPane.showMessageDialog(this, "Please verify the password (min 8).");
        }
    }//GEN-LAST:event_txtCOpwdActionPerformed

    private boolean nullCheck() {
        if (txtCOid.getText().length() != 0 && txtCOname.getText().length() != 0
                && txtCOPhone.getText().length() != 0 && txtCOAdd.getText().length() != 0 && txtCOCity.getText().length() != 0
                && txtCOState.getText().length() != 0 && txtCOZip.getText().length() != 0 && txtCOAgent.getText().length() != 0
                && txtCOAgentuname.getText().length() != 0 && txtCOpwd.getText().length() != 0 && txtCOpwd1.getText().length() != 0) {
            return false;
        } else {
            return true;
        }
    }

    private void clearfields() {
        txtCOname.setText("");
        txtCOPhone.setText("");
        txtCOAdd.setText("");
        txtCOCity.setText("");
        txtCOState.setText("");
        txtCOZip.setText("");
        txtCOAgent.setText("");
        txtCOAgentuname.setText("");
        txtCOpwd.setText("");
        txtCOpwd1.setText("");
        txtCOid.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnCOCancel;
    private javax.swing.JButton btnCOSubmit;
    private javax.swing.JLabel lblAddNonGovtOrgTitle;
    private javax.swing.JLabel lblCOAdd;
    private javax.swing.JLabel lblCOAgent;
    private javax.swing.JLabel lblCOAgentuname;
    private javax.swing.JLabel lblCOCity;
    private javax.swing.JLabel lblCOPhno;
    private javax.swing.JLabel lblCOState;
    private javax.swing.JLabel lblCOZip;
    private javax.swing.JLabel lblCOid;
    private javax.swing.JLabel lblCOname;
    private javax.swing.JLabel lblCOpwd;
    private javax.swing.JLabel lblCOpwd1;
    private javax.swing.JLabel lblNonGovtOrgAdmin1;
    private javax.swing.JLabel lblNonGovtOrgPhone1;
    private javax.swing.JLabel lblNonGovtOrgZip1;
    private javax.swing.JLabel lblNonGovtOrgid2;
    private javax.swing.JLabel lblNonGovtOrgname1;
    private javax.swing.JLabel lblNonGovtOrgpwd2;
    private javax.swing.JTextField txtCOAdd;
    private javax.swing.JTextField txtCOAgent;
    private javax.swing.JTextField txtCOAgentuname;
    private javax.swing.JTextField txtCOCity;
    private javax.swing.JTextField txtCOPhone;
    private javax.swing.JTextField txtCOState;
    private javax.swing.JTextField txtCOZip;
    private javax.swing.JTextField txtCOid;
    private javax.swing.JTextField txtCOname;
    private javax.swing.JTextField txtCOpwd;
    private javax.swing.JTextField txtCOpwd1;
    // End of variables declaration//GEN-END:variables

    private boolean chkpwd() {
        if (txtCOpwd.getText().equals(txtCOpwd1.getText())) {
            return true;
        } else {
            return false;
        }
    }
}
