/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Worker.Worker;
import Business.DropOff.DropOff;
import Business.DropOff.DropOffDirectory;
import Business.DistributionHub.DistributionHub;
import Business.Role.DOManagerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.DonorRole.DonorProfilePanel;

/**
 *
 *@author reetikabhanushali
 */
public class AddDOPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    DropOffDirectory fcpd;
    UserAccountDirectory uad;

    public AddDOPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;

        // Use the UserAccountDirectory from EcoSystem
        if (ecosystem.getACDOFDirectory() == null) {
            ecosystem.setACDODirectory(new DropOffDirectory(ecosystem.getUserAccountDirectory()));
        }

        // Populate Distribution Hub ComboBox
        ArrayList<String> whList = new ArrayList<>();
        for (DistributionHub fcw : ecosystem.getACDDirectory().getFadList()) {
            whList.add(fcw.getDistributionHubName());
        }
        cbDistributionHub.setModel(new DefaultComboBoxModel<>(whList.toArray(new String[0])));
        setBG();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddPantryTitle = new javax.swing.JLabel();
        lblDropOffname = new javax.swing.JLabel();
        txtDropOffname = new javax.swing.JTextField();
        lblDropOffPhone = new javax.swing.JLabel();
        txtDropOffPhone = new javax.swing.JTextField();
        lblDropOffAdd = new javax.swing.JLabel();
        txtDropOffAdd = new javax.swing.JTextField();
        lblDropOffCity = new javax.swing.JLabel();
        txtDropOffCity = new javax.swing.JTextField();
        lblDropOffState = new javax.swing.JLabel();
        txtDropOffState = new javax.swing.JTextField();
        lblDropOffZip = new javax.swing.JLabel();
        txtDropOffZip = new javax.swing.JTextField();
        lblDropOffManager = new javax.swing.JLabel();
        txtDropOffManager = new javax.swing.JTextField();
        lblDropOffManagername = new javax.swing.JLabel();
        txtDropOffManagername = new javax.swing.JTextField();
        lblDropOffpwd = new javax.swing.JLabel();
        txtDropOffpwd = new javax.swing.JTextField();
        lblDropOffpwd1 = new javax.swing.JLabel();
        txtDropOffpwd1 = new javax.swing.JTextField();
        btnDropOffSubmit = new javax.swing.JButton();
        lblDistributionHubname = new javax.swing.JLabel();
        lblDropOffid = new javax.swing.JLabel();
        txtDropOffid = new javax.swing.JTextField();
        lblWHPantryname1 = new javax.swing.JLabel();
        lblPantryid1 = new javax.swing.JLabel();
        lblPantryname1 = new javax.swing.JLabel();
        lblPantryPhone1 = new javax.swing.JLabel();
        lblPantryAdd1 = new javax.swing.JLabel();
        lblPantryCity1 = new javax.swing.JLabel();
        lblPantryState1 = new javax.swing.JLabel();
        lblPantryZip1 = new javax.swing.JLabel();
        lblPantryManager1 = new javax.swing.JLabel();
        lblPantryuname1 = new javax.swing.JLabel();
        lblPantrypwd2 = new javax.swing.JLabel();
        lblPantrypwd3 = new javax.swing.JLabel();
        cbDistributionHub = new javax.swing.JComboBox<>();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddPantryTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddPantryTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblAddPantryTitle.setText("Add Drop Off");
        add(lblAddPantryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        lblDropOffname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffname.setText("Drop Off Name:");
        add(lblDropOffname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        txtDropOffname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffnameFocusLost(evt);
            }
        });
        add(txtDropOffname, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 136, 137, -1));

        lblDropOffPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffPhone.setText("Phone Number:");
        add(lblDropOffPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        txtDropOffPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffPhoneFocusLost(evt);
            }
        });
        add(txtDropOffPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 179, 137, -1));

        lblDropOffAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffAdd.setText("Address:");
        add(lblDropOffAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 226, -1, 20));

        txtDropOffAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtDropOffAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 222, 137, -1));

        lblDropOffCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffCity.setText("City:");
        add(lblDropOffCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        txtDropOffCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtDropOffCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 265, 137, -1));

        lblDropOffState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffState.setText("State:");
        add(lblDropOffState, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        txtDropOffState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffState.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDropOffStateActionPerformed(evt);
            }
        });
        add(txtDropOffState, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 308, 137, -1));

        lblDropOffZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffZip.setText("Zip:");
        add(lblDropOffZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        txtDropOffZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffZipFocusLost(evt);
            }
        });
        txtDropOffZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDropOffZipActionPerformed(evt);
            }
        });
        add(txtDropOffZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 351, 137, -1));

        lblDropOffManager.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffManager.setText("Drop Off Manager Name:");
        add(lblDropOffManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        txtDropOffManager.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffManager.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffManagerFocusLost(evt);
            }
        });
        add(txtDropOffManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 394, 137, -1));

        lblDropOffManagername.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffManagername.setText("Drop Off Manager Username:");
        add(lblDropOffManagername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        txtDropOffManagername.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffManagername.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffManagername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffManagernameFocusLost(evt);
            }
        });
        add(txtDropOffManagername, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 437, 137, -1));

        lblDropOffpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffpwd.setText("Password:");
        add(lblDropOffpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        txtDropOffpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDropOffpwdActionPerformed(evt);
            }
        });
        add(txtDropOffpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 480, 137, -1));

        lblDropOffpwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffpwd1.setText("Confirm Password:");
        add(lblDropOffpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        txtDropOffpwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffpwd1.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffpwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffpwd1FocusLost(evt);
            }
        });
        add(txtDropOffpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 523, 137, -1));

        btnDropOffSubmit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnDropOffSubmit.setText("Submit");
        btnDropOffSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropOffSubmitActionPerformed(evt);
            }
        });
        add(btnDropOffSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, -1, -1));

        lblDistributionHubname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDistributionHubname.setText("Distribution Hub Name:");
        add(lblDistributionHubname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        lblDropOffid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDropOffid.setText("Drop Off ID:");
        add(lblDropOffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        txtDropOffid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtDropOffid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDropOffid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDropOffidFocusLost(evt);
            }
        });
        add(txtDropOffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 94, 137, -1));

        lblWHPantryname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblWHPantryname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 53, -1, -1));

        lblPantryid1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 94, -1, -1));

        lblPantryname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 136, -1, -1));

        lblPantryPhone1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 179, -1, -1));

        lblPantryAdd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 222, -1, -1));

        lblPantryCity1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 265, -1, -1));

        lblPantryState1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 308, -1, -1));

        lblPantryZip1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 351, -1, -1));

        lblPantryManager1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryManager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 394, -1, -1));

        lblPantryuname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantryuname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 437, -1, -1));

        lblPantrypwd2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantrypwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 480, -1, -1));

        lblPantrypwd3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(lblPantrypwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 523, -1, -1));

        cbDistributionHub.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbDistributionHub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbDistributionHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 700));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtDropOffnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffnameFocusLost
        // TODO add your handling code here:
        if (!(txtDropOffname.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryname1.setText("");
        }
    }//GEN-LAST:event_txtDropOffnameFocusLost

    private void txtDropOffPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffPhoneFocusLost
        // TODO add your handling code here:
        if (!(txtDropOffPhone.getText().matches("^[0-9]*$")) || !(txtDropOffPhone.getText().length() == 10)) {
            lblPantryPhone1.setText("Please enter a valid phone number");
        } else {
            lblPantryPhone1.setText("");

        }
    }//GEN-LAST:event_txtDropOffPhoneFocusLost

    private void txtDropOffZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffZipFocusLost
        // TODO add your handling code here:
        if ((txtDropOffZip.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryZip1.setText("Invalid input. Please enter only numbers");
        } else {
            lblPantryZip1.setText("");
        }
    }//GEN-LAST:event_txtDropOffZipFocusLost

    private void txtDropOffManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffManagerFocusLost
        // TODO add your handling code here:
        if (!(txtDropOffManager.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryManager1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryManager1.setText("");
        }
    }//GEN-LAST:event_txtDropOffManagerFocusLost

    public boolean isValid(String test, String regex) {
//        String regex = "^[A-Za-z0-9]+";
        Pattern p = Pattern.compile(regex);

        if (test == null) {
            return false;
        }

        Matcher m = p.matcher(test);

        return m.matches();
    }


    private void btnDropOffSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropOffSubmitActionPerformed
        // TODO add your handling code here:

        if (!nullCheck()) {
            if (chkpwd()) {

                String panid = txtDropOffid.getText();
                String panName = txtDropOffname.getText();
                String phone = txtDropOffPhone.getText();

                String panCity = txtDropOffCity.getText();
                String panState = txtDropOffState.getText();
                String panZip = txtDropOffZip.getText();
                String panManager = txtDropOffManager.getText();
                String panUser = txtDropOffManagername.getText();
                String panPswd = txtDropOffpwd.getText();
                if (!isValid(panid, "^[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid ID");
                    return;
                }
                if (!isValid(panName, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid name");
                    return;
                }
                if (!isValid(phone, "[+]?[0-9]{10,13}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid phone number");
                    return;
                }
                if (!isValid(panCity, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid city");
                    return;
                }
                if (!isValid(panState, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){2,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid state");
                    return;
                }
                if (!isValid(panZip, "^[0-9]{5}(?:-[0-9]{4})?$")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid zip");
                    return;
                }
                if (!isValid(panManager, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid name");
                    return;
                }
                if (!isValid(panUser, "^[a-zA-Z0-9._-]{6,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid username of atleast 6 characters");
                    return;
                }
                if (!isValid(panPswd, "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password of atleast 8 characters in length. It must contain a number, a specicial character, a lowercase and an uppercase character.");
                    return;
                }

                UserAccountDirectory uaList = ecosystem.getUserAccountDirectory();
                Worker employee = new Worker();
                employee.setName(txtDropOffManager.getText());
                String role = "FCPManager";
                DropOff fcp = new DropOff();
                fcp.setDropOffId("fcp" + txtDropOffid.getText());
                fcp.setDropOffHubName(cbDistributionHub.getSelectedItem().toString());
                fcp.setDropOffName(txtDropOffname.getText());
                fcp.setDropOffPhone(txtDropOffPhone.getText());
                fcp.setDropOffAddress(txtDropOffAdd.getText());
                fcp.setDropOffCity(txtDropOffCity.getText());
                fcp.setDropOffState(txtDropOffState.getText());
                fcp.setDropOffZipcode(txtDropOffZip.getText());
                fcp.setDropOffManager(txtDropOffManager.getText());
                UserAccount fcPantryAccount = new UserAccount();
                fcPantryAccount.setUsername(txtDropOffManagername.getText());
                fcPantryAccount.setPassword(txtDropOffpwd.getText());
                fcPantryAccount.setRole(new DOManagerRole());
                fcPantryAccount.setEmployee(employee);
                uad = ecosystem.getUserAccountDirectory();
                uad.createUserAccount(txtDropOffManagername.getText(), txtDropOffpwd.getText(), employee, new DOManagerRole());
                ecosystem.setUserAccountDirectory(uad);
                fcp.setDropOffAccount(fcPantryAccount);
                System.out.println(fcp);
                System.out.println("here");
                fcpd = ecosystem.getACDOFDirectory();
                fcpd.addNewDO(fcp);
                System.out.println(fcpd);
                System.out.println(ecosystem.getACDOFDirectory().getFcpList());

                ecosystem.setACDODirectory(fcpd);
                Integer pantryCnt = ecosystem.getDropOffCnt();
                ecosystem.setDropOffCnt(pantryCnt+1);

                JOptionPane.showMessageDialog(this, "Drop-Off added successfully!");
                clearfields();
                //  fcPantryAccount.setRole(new FCAdminRole());
                //fcp.setFcpAccount(fcPantryAccount);
                // ecosystem.getFCPDirectory().addNewFCPantry(fcp);
            } else {
                JOptionPane.showMessageDialog(this, "Password Mismatch. Please verify the password entered.");
                txtDropOffpwd1.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all mandatory fields");
        }
    }//GEN-LAST:event_btnDropOffSubmitActionPerformed

    private void txtDropOffStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDropOffStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDropOffStateActionPerformed

    private void txtDropOffZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDropOffZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDropOffZipActionPerformed

    private void txtDropOffidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffidFocusLost
        // TODO add your handling code here:
        if ((txtDropOffid.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryid1.setText("Invalid input. Please enter only numbers");
        } else {
            lblPantryid1.setText("");
        }
    }//GEN-LAST:event_txtDropOffidFocusLost

    private void txtDropOffManagernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffManagernameFocusLost
        // TODO add your handling code here:
        if (!(txtDropOffManagername.getText().matches("^[a-zA-Z]*$"))) {
            lblPantryuname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblPantryuname1.setText("");
        }
    }//GEN-LAST:event_txtDropOffManagernameFocusLost


    private void txtDropOffpwd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDropOffpwd1FocusLost
        // TODO add your handling code here:
//        if(!(txtFCPpwd.getText().equals(txtFCPpwd1.getText()))){
//            lblFCApwd2.setText("Password Mismatch. Please verify the password entered.");
//        }
//        else{
//            lblFCApwd2.setText("");
//        }
    }//GEN-LAST:event_txtDropOffpwd1FocusLost

    private void txtDropOffpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDropOffpwdActionPerformed

        if (!Business.Validations.ValidateInputs.isPasswordValid(txtDropOffpwd.getText())) {
            JOptionPane.showMessageDialog(this, "Please verify the password (min 8).");
        }
    }//GEN-LAST:event_txtDropOffpwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnDropOffSubmit;
    private javax.swing.JComboBox<String> cbDistributionHub;
    private javax.swing.JLabel lblAddPantryTitle;
    private javax.swing.JLabel lblDistributionHubname;
    private javax.swing.JLabel lblDropOffAdd;
    private javax.swing.JLabel lblDropOffCity;
    private javax.swing.JLabel lblDropOffManager;
    private javax.swing.JLabel lblDropOffManagername;
    private javax.swing.JLabel lblDropOffPhone;
    private javax.swing.JLabel lblDropOffState;
    private javax.swing.JLabel lblDropOffZip;
    private javax.swing.JLabel lblDropOffid;
    private javax.swing.JLabel lblDropOffname;
    private javax.swing.JLabel lblDropOffpwd;
    private javax.swing.JLabel lblDropOffpwd1;
    private javax.swing.JLabel lblPantryAdd1;
    private javax.swing.JLabel lblPantryCity1;
    private javax.swing.JLabel lblPantryManager1;
    private javax.swing.JLabel lblPantryPhone1;
    private javax.swing.JLabel lblPantryState1;
    private javax.swing.JLabel lblPantryZip1;
    private javax.swing.JLabel lblPantryid1;
    private javax.swing.JLabel lblPantryname1;
    private javax.swing.JLabel lblPantrypwd2;
    private javax.swing.JLabel lblPantrypwd3;
    private javax.swing.JLabel lblPantryuname1;
    private javax.swing.JLabel lblWHPantryname1;
    private javax.swing.JTextField txtDropOffAdd;
    private javax.swing.JTextField txtDropOffCity;
    private javax.swing.JTextField txtDropOffManager;
    private javax.swing.JTextField txtDropOffManagername;
    private javax.swing.JTextField txtDropOffPhone;
    private javax.swing.JTextField txtDropOffState;
    private javax.swing.JTextField txtDropOffZip;
    private javax.swing.JTextField txtDropOffid;
    private javax.swing.JTextField txtDropOffname;
    private javax.swing.JTextField txtDropOffpwd;
    private javax.swing.JTextField txtDropOffpwd1;
    // End of variables declaration//GEN-END:variables

    private boolean nullCheck() {
        if (txtDropOffid.getText().length() != 0 && txtDropOffname.getText().length() != 0
                && txtDropOffPhone.getText().length() != 0 && txtDropOffAdd.getText().length() != 0 && txtDropOffCity.getText().length() != 0
                && txtDropOffState.getText().length() != 0 && txtDropOffZip.getText().length() != 0 && txtDropOffManager.getText().length() != 0
                && txtDropOffManagername.getText().length() != 0 && txtDropOffpwd.getText().length() != 0 && txtDropOffpwd1.getText().length() != 0) {
            return false;
        } else {
            return true;
        }
    }

    private void clearfields() {
        txtDropOffid.setText("");
        txtDropOffname.setText("");
        cbDistributionHub.setSelectedIndex(0);
        txtDropOffPhone.setText("");
        txtDropOffAdd.setText("");
        txtDropOffCity.setText("");
        txtDropOffState.setText("");
        txtDropOffZip.setText("");
        txtDropOffManager.setText("");
        txtDropOffManagername.setText("");
        txtDropOffpwd.setText("");
        txtDropOffpwd1.setText("");
    }

    private boolean chkpwd() {
        if (txtDropOffpwd.getText().equals(txtDropOffpwd1.getText())) {
            return true;
        } else {
            return false;
        }
    }
}
