/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 *@author reetikabhanushali
 */
public class ManageCOJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCOJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;

    public ManageCOJPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer = userProcessContainer;
        lblNGObgc.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblNGObgc.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
        lblNGObgc.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

        Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
        lblNGObgc.setIcon(new ImageIcon(newimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneNonGovtOrg = new javax.swing.JSplitPane();
        NonGovtOrgControlPanel = new javax.swing.JPanel();
        btnCOAddCO = new javax.swing.JButton();
        btnCOView = new javax.swing.JButton();
        SysAdminNGOWorkareaPanel = new javax.swing.JPanel();
        lblNGObgc = new javax.swing.JLabel();

        NonGovtOrgControlPanel.setBackground(new java.awt.Color(255, 255, 255));
        NonGovtOrgControlPanel.setPreferredSize(new java.awt.Dimension(150, 600));

        btnCOAddCO.setBackground(new java.awt.Color(204, 204, 255));
        btnCOAddCO.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnCOAddCO.setText("Add CO");
        btnCOAddCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOAddCOActionPerformed(evt);
            }
        });

        btnCOView.setBackground(new java.awt.Color(204, 204, 255));
        btnCOView.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnCOView.setText("View/Modify");
        btnCOView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NonGovtOrgControlPanelLayout = new javax.swing.GroupLayout(NonGovtOrgControlPanel);
        NonGovtOrgControlPanel.setLayout(NonGovtOrgControlPanelLayout);
        NonGovtOrgControlPanelLayout.setHorizontalGroup(
            NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NonGovtOrgControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCOView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCOAddCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NonGovtOrgControlPanelLayout.setVerticalGroup(
            NonGovtOrgControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NonGovtOrgControlPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnCOAddCO)
                .addGap(26, 26, 26)
                .addComponent(btnCOView)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        SplitPaneNonGovtOrg.setLeftComponent(NonGovtOrgControlPanel);

        SysAdminNGOWorkareaPanel.setPreferredSize(new java.awt.Dimension(840, 600));

        javax.swing.GroupLayout SysAdminNGOWorkareaPanelLayout = new javax.swing.GroupLayout(SysAdminNGOWorkareaPanel);
        SysAdminNGOWorkareaPanel.setLayout(SysAdminNGOWorkareaPanelLayout);
        SysAdminNGOWorkareaPanelLayout.setHorizontalGroup(
            SysAdminNGOWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNGObgc, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        SysAdminNGOWorkareaPanelLayout.setVerticalGroup(
            SysAdminNGOWorkareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNGObgc, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        SplitPaneNonGovtOrg.setRightComponent(SysAdminNGOWorkareaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNonGovtOrg, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneNonGovtOrg)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCOAddCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOAddCOActionPerformed
        try {
            // TODO add your handling code here:
            AddCOPanel objAddNGO = new AddCOPanel(userProcessContainer,ecosystem);
            SplitPaneNonGovtOrg.setRightComponent(objAddNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageCOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCOAddCOActionPerformed

    private void btnCOViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOViewActionPerformed
        try {
            // TODO add your handling code here:
            ViewModifyCOPanel objViewModNGO = new ViewModifyCOPanel(userProcessContainer,ecosystem);
            SplitPaneNonGovtOrg.setRightComponent(objViewModNGO);
        } catch (IOException ex) {
            Logger.getLogger(ManageCOJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCOViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NonGovtOrgControlPanel;
    private javax.swing.JSplitPane SplitPaneNonGovtOrg;
    private javax.swing.JPanel SysAdminNGOWorkareaPanel;
    private javax.swing.JButton btnCOAddCO;
    private javax.swing.JButton btnCOView;
    private javax.swing.JLabel lblNGObgc;
    // End of variables declaration//GEN-END:variables
}
