/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Worker.Worker;
import Business.CommunityOutreach.CommunityOutreach;
import Business.CommunityOutreach.CommunityOutreachDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import ui.DonorRole.DonorProfilePanel;

/**
 *
 *@author reetikabhanushali
 */
public class ViewModifyCOPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewModifyCOPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CommunityOutreachDirectory ngod;

    public ViewModifyCOPanel(JPanel userProcessContainer, EcoSystem ecosystem) throws IOException {
        initComponents();

//        imageLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//        imageLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//        Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));
//
//        Image newimg = img.getScaledInstance(userProcessContainer.getWidth(), userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//        imageLbl.setIcon(new ImageIcon(newimg));
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        if (ecosystem.getcoDir() == null) {
            ecosystem.setNgoDir(new CommunityOutreachDirectory());
        }
        addDummyData();
        populatengotable();
        txtCOuname.setEnabled(false);
        setBG();
        makeTableTransparent();
    }
    
    private void addDummyData() {
    // Check if the list already has data to avoid duplication
        if (!ecosystem.getcoDir().getNgoList().isEmpty()) {
            return;
        }

        // Create dummy NGOs
        CommunityOutreach ngo1 = new CommunityOutreach();
        ngo1.setCOId("CO001");
        ngo1.setCOName("Helping Hands");
        ngo1.setCOAgent("Alice Johnson");
        ngo1.setCOPhone("1234567890");
        ngo1.setCOAddress("123 Main St");
        ngo1.setCOCity("New York");
        ngo1.setCOState("NY");
        ngo1.setCOZipcode("10001");

        UserAccount account1 = new UserAccount();
        account1.setUsername("alice_johnson");
        account1.setPassword("Password@123");
        Worker worker1 = new Worker();
        worker1.setName("Alice Johnson");
        account1.setEmployee(worker1);
        ngo1.setCOAccount(account1);

        CommunityOutreach ngo2 = new CommunityOutreach();
        ngo2.setCOId("CO002");
        ngo2.setCOName("Care and Share");
        ngo2.setCOAgent("Bob Smith");
        ngo2.setCOPhone("9876543210");
        ngo2.setCOAddress("456 Elm St");
        ngo2.setCOCity("Los Angeles");
        ngo2.setCOState("CA");
        ngo2.setCOZipcode("90001");

        UserAccount account2 = new UserAccount();
        account2.setUsername("bob_smith");
        account2.setPassword("Password@456");
        Worker worker2 = new Worker();
        worker2.setName("Bob Smith");
        account2.setEmployee(worker2);
        ngo2.setCOAccount(account2);

        // Add the NGOs to the directory
        ecosystem.getcoDir().addNewNGO(ngo1);
        ecosystem.getcoDir().addNewNGO(ngo2);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCOTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblNonGovtOrg = new javax.swing.JTable();
        btnCODelete = new javax.swing.JButton();
        btnCOEdit = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        lblCOname = new javax.swing.JLabel();
        txtCOname = new javax.swing.JTextField();
        lblCOPhone = new javax.swing.JLabel();
        txtCOPhone = new javax.swing.JTextField();
        lblCOAdd = new javax.swing.JLabel();
        txtCOAdd = new javax.swing.JTextField();
        lblCOCity = new javax.swing.JLabel();
        txtCOCity = new javax.swing.JTextField();
        lblCOState = new javax.swing.JLabel();
        txtCOState = new javax.swing.JTextField();
        lblCOZip = new javax.swing.JLabel();
        txtCOZip = new javax.swing.JTextField();
        lblCOAgent = new javax.swing.JLabel();
        txtCOAgent = new javax.swing.JTextField();
        lblCOuname = new javax.swing.JLabel();
        txtCOuname = new javax.swing.JTextField();
        lblCOpwd = new javax.swing.JLabel();
        txtCOpwd = new javax.swing.JTextField();
        btnCOUpdate = new javax.swing.JButton();
        lblCOname1 = new javax.swing.JLabel();
        lblCOPhone1 = new javax.swing.JLabel();
        lblCOAdd1 = new javax.swing.JLabel();
        lblCOCity1 = new javax.swing.JLabel();
        lblCOState1 = new javax.swing.JLabel();
        lblCOZip1 = new javax.swing.JLabel();
        lblCOAgent1 = new javax.swing.JLabel();
        lblCOuname1 = new javax.swing.JLabel();
        lblCOpwd1 = new javax.swing.JLabel();
        lblCOid1 = new javax.swing.JLabel();
        btnCOCancel = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();
        lblCOid = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddCOTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblAddCOTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblAddCOTitle.setText("CO Details");
        add(lblAddCOTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 190, 40));

        tblNonGovtOrg.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblNonGovtOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CO ID", "Name", "Agent Name", "Phone Number", "Address", "City", "State", "Zip"
            }
        ));
        tblNonGovtOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNonGovtOrgMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblNonGovtOrg);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 820, 130));

        btnCODelete.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCODelete.setText("Delete");
        btnCODelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCODeleteActionPerformed(evt);
            }
        });
        add(btnCODelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 92, -1));

        btnCOEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCOEdit.setText("Edit");
        btnCOEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOEditActionPerformed(evt);
            }
        });
        add(btnCOEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 92, -1));

        jPanel.setOpaque(false);
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCOname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOname.setText("CO Name:");
        jPanel.add(lblCOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        txtCOname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOnameFocusLost(evt);
            }
        });
        txtCOname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCOnameKeyReleased(evt);
            }
        });
        jPanel.add(txtCOname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 137, -1));

        lblCOPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOPhone.setText("Phone Number:");
        jPanel.add(lblCOPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtCOPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOPhone.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOPhoneFocusLost(evt);
            }
        });
        txtCOPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCOPhoneKeyReleased(evt);
            }
        });
        jPanel.add(txtCOPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 137, -1));

        lblCOAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOAdd.setText("CO Address:");
        jPanel.add(lblCOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtCOAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel.add(txtCOAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 137, -1));

        lblCOCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOCity.setText("City :");
        jPanel.add(lblCOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        txtCOCity.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOCity.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel.add(txtCOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 137, -1));

        lblCOState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOState.setText("State :");
        jPanel.add(lblCOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtCOState.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOState.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel.add(txtCOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 137, -1));

        lblCOZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOZip.setText("Zip:");
        jPanel.add(lblCOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtCOZip.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOZipFocusLost(evt);
            }
        });
        jPanel.add(txtCOZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 137, -1));

        lblCOAgent.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOAgent.setText("CO Agent Name:");
        jPanel.add(lblCOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtCOAgent.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtCOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCOAgentFocusLost(evt);
            }
        });
        jPanel.add(txtCOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 137, -1));

        lblCOuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOuname.setText("CO Agent Username :");
        jPanel.add(lblCOuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtCOuname.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOuname.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel.add(txtCOuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 137, -1));

        lblCOpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOpwd.setText("Password :");
        jPanel.add(lblCOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 25));

        txtCOpwd.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtCOpwd.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel.add(txtCOpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 137, -1));

        btnCOUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCOUpdate.setText("Update");
        btnCOUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOUpdateActionPerformed(evt);
            }
        });
        jPanel.add(btnCOUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 92, -1));

        lblCOname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 58, 360, 20));

        lblCOPhone1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 98, 360, 20));

        lblCOAdd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 138, 360, 20));

        lblCOCity1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 178, 360, 20));

        lblCOState1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 218, 360, 20));

        lblCOZip1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 246, 360, 20));

        lblCOAgent1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOAgent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 298, 360, 20));

        lblCOuname1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOuname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 338, 360, 20));

        lblCOpwd1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 378, 360, 20));

        lblCOid1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jPanel.add(lblCOid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 28, 150, 20));

        btnCOCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnCOCancel.setText("Cancel");
        btnCOCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOCancelActionPerformed(evt);
            }
        });
        jPanel.add(btnCOCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 660, -1));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1490, 770));

        lblCOid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOid.setText("CO Id:");
        add(lblCOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void makeTableTransparent() {
        tblNonGovtOrg.setOpaque(false);
        ((DefaultTableCellRenderer) tblNonGovtOrg.getDefaultRenderer(Object.class)).setOpaque(false);
        tblNonGovtOrg.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblNonGovtOrg.getModel().getColumnCount(); i++) {
            tblNonGovtOrg.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    private void btnCODeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCODeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNonGovtOrg.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNonGovtOrg.getModel();
        CommunityOutreach selectedNGO = (CommunityOutreach) model.getValueAt(selectedRowIndex, 0);
        ecosystem.getUserAccountDirectory().deleteUserAccount(
                ecosystem.getcoDir().getNgoList().get(selectedRowIndex).getCOAccount());
        ngod = ecosystem.getcoDir();
        ngod.deleteNGO(selectedNGO);
        ecosystem.setNgoDir(ngod);
        Integer ngoCnt = ecosystem.getcoCnt();
        ecosystem.setcoCnt(ngoCnt - 1);
        JOptionPane.showMessageDialog(this, "NGO deleted Successfully");
        populatengotable();
        clearfields();
    }//GEN-LAST:event_btnCODeleteActionPerformed

    private void btnCOEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOEditActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNonGovtOrg.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to Edit");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNonGovtOrg.getModel();
        CommunityOutreach selectedNGO = (CommunityOutreach) model.getValueAt(selectedRowIndex, 0);
        lblCOid1.setText(selectedNGO.getCOId());
        txtCOname.setText(selectedNGO.getCOName());
        txtCOPhone.setText(selectedNGO.getCOPhone());
        txtCOAdd.setText(selectedNGO.getCOAddress());
        txtCOCity.setText(selectedNGO.getCOCity());
        txtCOState.setText(selectedNGO.getCOState());
        txtCOZip.setText(selectedNGO.getCOZipcode());
        txtCOAgent.setText(selectedNGO.getCOAgent());
        txtCOuname.setText(selectedNGO.getCOAccount().getUsername());
        txtCOpwd.setText(selectedNGO.getCOAccount().getPassword());
    }//GEN-LAST:event_btnCOEditActionPerformed

    private void txtCOnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOnameFocusLost
        // TODO add your handling code here:
        if (!(txtCOname.getText().matches("^[a-zA-Z]*$"))) {
            lblCOname1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblCOname1.setText("");
        }
    }//GEN-LAST:event_txtCOnameFocusLost

    private void txtCOnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOnameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCOnameKeyReleased

    private void txtCOPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOPhoneFocusLost
        // TODO add your handling code here:
        if (!(txtCOPhone.getText().matches("^[0-9]*$")) || !(txtCOPhone.getText().length() == 10)) {
            lblCOPhone1.setText("Please enter a valid phone number");
        } else {
            lblCOPhone1.setText("");

        }
    }//GEN-LAST:event_txtCOPhoneFocusLost

    private void txtCOPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOPhoneKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCOPhoneKeyReleased

    private void txtCOZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOZipFocusLost
        // TODO add your handling code here:
        if ((txtCOZip.getText().matches("^[a-zA-Z]*$"))) {
            lblCOZip1.setText("Invalid input. Please enter only numbers");
        } else {
            lblCOZip1.setText("");
        }
    }//GEN-LAST:event_txtCOZipFocusLost

    private void txtCOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCOAgentFocusLost
        // TODO add your handling code here:
        if (!(txtCOAgent.getText().matches("^[a-zA-Z]*$"))) {
            lblCOAgent1.setText("Invalid input. Please enter only alphabets");
        } else {
            lblCOAgent1.setText("");
        }
    }//GEN-LAST:event_txtCOAgentFocusLost

    public boolean isValid(String test, String regex) {
//        String regex = "^[A-Za-z0-9]+";
        Pattern p = Pattern.compile(regex);

        if (test == null) {
            return false;
        }

        Matcher m = p.matcher(test);

        return m.matches();
    }

    private void btnCOUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblNonGovtOrg.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblNonGovtOrg.getModel();
        String NGOid = lblCOid1.getText();

        ArrayList<CommunityOutreach> nogList = ecosystem.getcoDir().getNgoList();
        for (CommunityOutreach f : nogList) {
            if (f.getCOId().equals(NGOid)) {

                String ngoName = txtCOname.getText();
                String phone = txtCOPhone.getText();

                String ngoCity = txtCOCity.getText();
                String ngoState = txtCOState.getText();
                String ngoZip = txtCOZip.getText();
                String ngoAgent = txtCOAgent.getText();
                String ngoUser = txtCOuname.getText();
                String ngoPswd = txtCOpwd.getText();
                
                if (!isValid(ngoName, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid name");
                    return;
                }
                if (!isValid(phone, "[+]?[0-9]{10,13}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid phone number");
                    return;
                }
                if (!isValid(ngoCity, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid city");
                    return;
                }
                if (!isValid(ngoState, "([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+){2,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid state");
                    return;
                }
                if (!isValid(ngoZip, "^[0-9]{5}(?:-[0-9]{4})?$")) {
                    JOptionPane.showMessageDialog(this, "Please enter valid zip");
                    return;
                }
                if (!isValid(ngoAgent, "^[A-Za-z]{3,}")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid name");
                    return;
                }
                if (!isValid(ngoUser, "^[a-zA-Z0-9._-]{6,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid username of atleast 6 characters");
                    return;
                }
                if (!isValid(ngoPswd, "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid password of atleast 8 characters in length. It must contain a number, a specicial character, a lowercase and an uppercase character.");
                    return;
                }

                f.setCOName(txtCOname.getText());
                f.setCOPhone(txtCOPhone.getText());
                f.setCOAddress(txtCOAdd.getText());
                f.setCOCity(txtCOCity.getText());
                f.setCOState(txtCOState.getText());
                f.setCOZipcode(txtCOZip.getText());
                f.setCOAgent(txtCOAgent.getText());
                UserAccount NGOua = new UserAccount();
                NGOua.setUsername(txtCOuname.getText());
                NGOua.setPassword(txtCOpwd.getText());
                Worker emp = new Worker();
                emp.setName(txtCOAgent.getText());
                NGOua.setEmployee(emp);
                f.setCOAccount(NGOua);
                break;
            }

        }
        // ecosystem.setFCWDirectory(fcWarehouseList);
        ngod = ecosystem.getcoDir();
        ecosystem.setNgoDir(ngod);
        JOptionPane.showMessageDialog(this, "NGO details updated successfully");
        clearfields();
        populatengotable();
    }//GEN-LAST:event_btnCOUpdateActionPerformed

    private void tblNonGovtOrgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNonGovtOrgMousePressed
        // TODO add your handling code here:
        tblNonGovtOrg.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblNonGovtOrgMousePressed

    private void btnCOCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCOCancelActionPerformed

    private void populatengotable() {
        DefaultTableModel model = (DefaultTableModel) tblNonGovtOrg.getModel();
        model.setRowCount(0);
        for (CommunityOutreach ngo : ecosystem.getcoDir().getNgoList()) {
            Object[] row = new Object[8];
            row[0] = ngo;
            row[1] = ngo.getCOName();
            row[2] = ngo.getCOAgent();
            row[3] = ngo.getCOPhone();
            row[4] = ngo.getCOAddress();
            row[5] = ngo.getCOCity();
            row[6] = ngo.getCOState();
            row[7] = ngo.getCOZipcode();
            model.addRow(row);
        }
    }

    private void clearfields() {
        txtCOname.setText("");
        txtCOPhone.setText("");
        txtCOAdd.setText("");
        txtCOCity.setText("");
        txtCOState.setText("");
        txtCOZip.setText("");
        txtCOAgent.setText("");
        txtCOuname.setText("");
        txtCOpwd.setText("");
        lblCOid1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnCOCancel;
    private javax.swing.JButton btnCODelete;
    private javax.swing.JButton btnCOEdit;
    private javax.swing.JButton btnCOUpdate;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAddCOTitle;
    private javax.swing.JLabel lblCOAdd;
    private javax.swing.JLabel lblCOAdd1;
    private javax.swing.JLabel lblCOAgent;
    private javax.swing.JLabel lblCOAgent1;
    private javax.swing.JLabel lblCOCity;
    private javax.swing.JLabel lblCOCity1;
    private javax.swing.JLabel lblCOPhone;
    private javax.swing.JLabel lblCOPhone1;
    private javax.swing.JLabel lblCOState;
    private javax.swing.JLabel lblCOState1;
    private javax.swing.JLabel lblCOZip;
    private javax.swing.JLabel lblCOZip1;
    private javax.swing.JLabel lblCOid;
    private javax.swing.JLabel lblCOid1;
    private javax.swing.JLabel lblCOname;
    private javax.swing.JLabel lblCOname1;
    private javax.swing.JLabel lblCOpwd;
    private javax.swing.JLabel lblCOpwd1;
    private javax.swing.JLabel lblCOuname;
    private javax.swing.JLabel lblCOuname1;
    private javax.swing.JTable tblNonGovtOrg;
    private javax.swing.JTextField txtCOAdd;
    private javax.swing.JTextField txtCOAgent;
    private javax.swing.JTextField txtCOCity;
    private javax.swing.JTextField txtCOPhone;
    private javax.swing.JTextField txtCOState;
    private javax.swing.JTextField txtCOZip;
    private javax.swing.JTextField txtCOname;
    private javax.swing.JTextField txtCOpwd;
    private javax.swing.JTextField txtCOuname;
    // End of variables declaration//GEN-END:variables
}
