/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DOManagerRole;

import Business.CommunityOutreach.CommunityOutreach;
import Business.EcoSystem;
import Business.DropOff.DropOff;
import Business.DistributionHub.DistributionHub;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author reetikabhanushali 
 */
public class ContactDHPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactDHPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String WHname;
    String FCPmgname;
    public ContactDHPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        lblRequestVol.setVisible(true);
        lblVolReq.setVisible(true);
        cbSelCO.setVisible(true);
        btnSubmitReq.setVisible(true);

        FCPmgname = userAcc.getEmployee().getName();
        for(DropOff fcp: ecosystem.getACDOFDirectory().getFcpList()){
            if(fcp.getDropOffManager().equals(FCPmgname)){
                 WHname = fcp.getDropOffHubName();
            }
        }
        setBG();
        populateCommunityOutreachComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDHTitle = new javax.swing.JLabel();
        lblCOName = new javax.swing.JLabel();
        cbSelCO = new javax.swing.JComboBox<>();
        btnSubmitReq = new javax.swing.JButton();
        lblVolReq = new javax.swing.JLabel();
        lblRequestVol = new javax.swing.JLabel();
        lblCO = new javax.swing.JLabel();
        cbVolReq1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDHTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblDHTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblDHTitle.setText("Contact Community Outreach");
        add(lblDHTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblCOName.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblCOName.setText("Community Outreach Name :");
        add(lblCOName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        cbSelCO.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbSelCO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "10", "20", "30", "40", "50" }));
        cbSelCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelCOActionPerformed(evt);
            }
        });
        add(cbSelCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, -1));

        btnSubmitReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnSubmitReq.setText("Submit Request");
        btnSubmitReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitReqActionPerformed(evt);
            }
        });
        add(btnSubmitReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        lblVolReq.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblVolReq.setText("Number of Volunteers Required :");
        add(lblVolReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        lblRequestVol.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblRequestVol.setText("Request Volunteers");
        add(lblRequestVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        lblCO.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCO.setText("Select Community Outreach");
        add(lblCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, -1));

        cbVolReq1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbVolReq1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "10", "20", "30", "40", "50" }));
        cbVolReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVolReq1ActionPerformed(evt);
            }
        });
        add(cbVolReq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

       public void setBG() {
        try {
//            LabelImage.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            LabelImage.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            LabelImage.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//            LabelImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }
    private void btnSubmitReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitReqActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Your request has been sent to Warehouse");
    }//GEN-LAST:event_btnSubmitReqActionPerformed

    private void cbSelCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelCOActionPerformed
        // TODO add your handling code here:
//        populateDistributionHubComboBox();
    }//GEN-LAST:event_cbSelCOActionPerformed

    private void cbVolReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVolReq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVolReq1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitReq;
    private javax.swing.JComboBox<String> cbSelCO;
    private javax.swing.JComboBox<String> cbVolReq1;
    private javax.swing.JLabel lblCO;
    private javax.swing.JLabel lblCOName;
    private javax.swing.JLabel lblDHTitle;
    private javax.swing.JLabel lblRequestVol;
    private javax.swing.JLabel lblVolReq;
    // End of variables declaration//GEN-END:variables

//    private void populatefields() {
//        for(DistributionHub fcw : ecosystem.getACDDirectory().getFadList()){
//            if(fcw.getDistributionHubName().equals(WHname)){
//                txtDHName.setText(fcw.getDistributionHubName());
//                txtDHPhone.setText(fcw.getDistributionHubPhone());
//                txtDHAdd.setText(fcw.getDistributionHubAddress());
//                txtDHCity.setText(fcw.getDistributionHubCity());
//                txtDHState.setText(fcw.getDistributionHubState());
//                txtDHZip.setText(fcw.getDistributionHubZipcode());
//                txtDHManager.setText(fcw.getDistributionHubAdmin());
//            }
//        }
//    }
    
    private void populateCommunityOutreachComboBox() {
    // Clear existing items
    cbSelCO.removeAllItems();
    cbSelCO.addItem("-select-"); // Default option

    // Fetch the list of community outreach centers
    for (CommunityOutreach co : ecosystem.getcoDir().getNgoList()) {
        cbSelCO.addItem(co.getCOName()); // Add community outreach names to combo box
    }
}

}
