/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DOManagerRole;

import Business.EcoSystem;
import Business.DropOff.DropOff;
import Business.DropOff.DropOffItems;
import Business.COVolunteer.COVolunteer;
import Business.AccessoryRequestorder.AccessoryRequestorder;
import Business.AccessoryRequestorder.AccessoryRequestorderDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reetikabhanushali 
 */
public class ViewItemsRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewItemsRequestsPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String volname;
    String FCPname;
    String FCPmgname;
    String WHname;
    String city;

    public ViewItemsRequestsPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        if (ecosystem.getReqorderDirectory() == null) {
            ecosystem.setReqorderDirectory(new AccessoryRequestorderDirectory());
        }
//        String FCAname = userAcc.getEmployee().getName();
//        WHname = ecosystem.getFCWDirectory().getWHname(FCAname);
        FCPmgname = userAcc.getEmployee().getName();
        for (DropOff fcp : ecosystem.getACDOFDirectory().getFcpList()) {
            if (fcp.getDropOffManager().equals(FCPmgname)) {
                FCPname = fcp.getDropOffName();
                city = fcp.getDropOffCity();
                System.out.println(FCPname + " pantry Fcp name");
                System.out.println(city + " pantry city name");
                
                break;
            }
        }
        ArrayList<String> VolunteerList = new ArrayList();
        for (COVolunteer vol : ecosystem.getVolDir().getVolunteerList()) {
            if (vol.getVolCity().equals(city) && vol.getVolAvail().equals("Yes")) {
                VolunteerList.add(vol.getVolName());
            }
        }
        ArrayList<String> donIdList = new ArrayList();

        for (DropOffItems fci : ecosystem.getACDOIDirectory().getDOiList()) {
            if (fci.getDropOffName().equals(FCPname)) {
                donIdList.add(fci.getDropOffItemId());
            }
        }

        cbAssignVol.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
//        asgvol.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
        cbDonationID.setModel(new DefaultComboBoxModel<String>(donIdList.toArray(new String[0])));
//        cbdonid.setModel(new DefaultComboBoxModel<String>(donIdList.toArray(new String[0])));
        populateTable();
//        setBG();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoodRequestsTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblAccessoryRequests = new javax.swing.JTable();
        btnRequestsAssign = new javax.swing.JButton();
        lblRequestsid = new javax.swing.JLabel();
        txtRequestsid = new javax.swing.JTextField();
        lblFoodRequestsid1 = new javax.swing.JLabel();
        btnRequestsSend = new javax.swing.JButton();
        lblFoodRequestsTitle1 = new javax.swing.JLabel();
        cbVolunteerLbl = new javax.swing.JLabel();
        cbAssignVol = new javax.swing.JComboBox<>();
        cbDonationID = new javax.swing.JComboBox<>();
        lblDonationID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoodRequestsTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 29)); // NOI18N
        lblFoodRequestsTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblFoodRequestsTitle.setText("View Accessory Requests");
        add(lblFoodRequestsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tblAccessoryRequests.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        tblAccessoryRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Requestor", "Quantity", "Order Type", "Status", "Donation ID"
            }
        ));
        tblAccessoryRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAccessoryRequestsMousePressed(evt);
            }
        });
        jScrollPane.setViewportView(tblAccessoryRequests);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 999, 153));

        btnRequestsAssign.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnRequestsAssign.setText("Assign");
        btnRequestsAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestsAssignActionPerformed(evt);
            }
        });
        add(btnRequestsAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        lblRequestsid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblRequestsid.setText("Request ID :");
        add(lblRequestsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtRequestsid.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        txtRequestsid.setPreferredSize(new java.awt.Dimension(150, 25));
        txtRequestsid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRequestsidFocusLost(evt);
            }
        });
        txtRequestsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRequestsidKeyReleased(evt);
            }
        });
        add(txtRequestsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 137, -1));

        lblFoodRequestsid1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblFoodRequestsid1.setText("Assign Volunteer :");
        add(lblFoodRequestsid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnRequestsSend.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        btnRequestsSend.setText("Send request to volunteer");
        btnRequestsSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestsSendActionPerformed(evt);
            }
        });
        add(btnRequestsSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, -1));

        lblFoodRequestsTitle1.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        lblFoodRequestsTitle1.setForeground(new java.awt.Color(102, 102, 255));
        lblFoodRequestsTitle1.setText("Assign Volunteer");
        add(lblFoodRequestsTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        cbVolunteerLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        add(cbVolunteerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -70, 780, 670));

        cbAssignVol.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbAssignVol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAssignVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAssignVolActionPerformed(evt);
            }
        });
        add(cbAssignVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 137, -1));

        cbDonationID.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        cbDonationID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDonationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDonationIDActionPerformed(evt);
            }
        });
        add(cbDonationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 100, -1));

        lblDonationID.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lblDonationID.setText("Donation ID:");
        add(lblDonationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

//    public void setBG() {
//        try {
//            cbVolunteerLbl.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            cbVolunteerLbl.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//            cbVolunteerLbl.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
//
//            Image img = ImageIO.read(getClass().getResource("/Images/background2.png"));
//
//            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
//            cbVolunteerLbl.setIcon(new ImageIcon(newimg));
//        } catch (IOException ex) {
//
//        }
//    }

    public void makeTableTransparent() {
        tblAccessoryRequests.setOpaque(false);
        ((DefaultTableCellRenderer) tblAccessoryRequests.getDefaultRenderer(Object.class)).setOpaque(false);
        tblAccessoryRequests.setShowGrid(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblAccessoryRequests.getModel().getColumnCount(); i++) {
            tblAccessoryRequests.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void txtRequestsidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRequestsidFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtRequestsidFocusLost

    private void txtRequestsidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequestsidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequestsidKeyReleased

    private void btnRequestsSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestsSendActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAccessoryRequests.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblAccessoryRequests.getModel();
        AccessoryRequestorder selectedR = (AccessoryRequestorder) model.getValueAt(selectedRowIndex, 0);
        txtRequestsid.setText(selectedR.getReqOrderId());
//        ArrayList<String> VolunteerList = new ArrayList();
//        for (COVolunteer vol : ecosystem.getVolDir().getVolunteerList()) {
//            VolunteerList.add(vol.getVolName());
//        }
//        cbAssignVol.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
    }//GEN-LAST:event_btnRequestsSendActionPerformed

    private void btnRequestsAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestsAssignActionPerformed
        // TODO add your handling code here:
        String Reqid = txtRequestsid.getText();
        String donId = cbDonationID.getSelectedItem().toString();
        System.out.println(donId + "don combo box");
        volname = cbAssignVol.getSelectedItem().toString();
        String reqQunty = "";
        Integer intReqQunty = 0;
        String donQnt = "";
        Integer intDonQnt = 0;
        DropOffItems donatItem = new DropOffItems();
        for (DropOffItems fcpi : ecosystem.getACDOIDirectory().getDOiList()) {
            System.out.println(fcpi.getDropOffItemId() + "fcpi item id is....");
            if (fcpi.getDropOffItemId()== null ? donId == null : fcpi.getDropOffItemId().equals(donId)) {
                donQnt = fcpi.getAccessoryQuantity();
                intDonQnt = Integer.parseInt(donQnt);
                donatItem = fcpi;
//                    ecosystem.getFCPIDirectory().deleteFCPItems(fcpi);
                break;
            }
        }

        for (AccessoryRequestorder r : ecosystem.getReqorderDirectory().getReqOrderList()) {
            if (r.getReqOrderId() == null ? Reqid == null : r.getReqOrderId().equals(Reqid)) {
                reqQunty = r.getReqOrderQuant();
                intReqQunty = Integer.parseInt(reqQunty);

                if (intReqQunty > intDonQnt) {
                    JOptionPane.showMessageDialog(this, " request quanty is greater than donation");
                    return;
                } else {
                    volname = cbAssignVol.getSelectedItem().toString();
                    r.setReqVol(volname);
                    r.setReqOrderStatus("Assigned to Volunteer");
                    r.setReqDonId(donId);
                    ecosystem.getACDOIDirectory().deleteFCPItems(donatItem);
                    String remQunt = String.valueOf(intDonQnt - intReqQunty);
                    donatItem.setAccessoryQuantity(remQunt);
                    if (!Objects.equals(intReqQunty, intDonQnt)) {
                        ecosystem.getACDOIDirectory().addFCPItems(donatItem);
                        System.out.println(donatItem + "donation item in fcp....");
                    }

                    for (COVolunteer v : ecosystem.getVolDir().getVolunteerList()) {
                        if (v.getVolName().equals(volname)) {
                            v.setVolAvail("No");
                        }
                    }
                    populateTable();
                }

                System.out.println(reqQunty + "req qunty is....");
            }
        }

//        for(COVolunteer v:ecosystem.getVolDir().getVolunteerList()){
//            if(v.getVolName().equals(volname)){
//                v.setVolAvail("No");
//            }
//        }
//        for(AccessoryDonation d : ecosystem.getDonatDirectory().getDonatList()){
//        System.out.println(d.getDonatId() + "donID");
//        if(d.getDonatId() == null ? donId == null : d.getDonatId().equals(donId)){
//             ecosystem.getDonatDirectory().deleteDonation(d);
//             System.out.println(d + "delete ");
//             break;
//        }
//    }
        JOptionPane.showMessageDialog(this, "Delivery Assigned to Volunteer Successfully!");
    }//GEN-LAST:event_btnRequestsAssignActionPerformed

    private void tblAccessoryRequestsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccessoryRequestsMousePressed
        // TODO add your handling code here:
        tblAccessoryRequests.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblAccessoryRequestsMousePressed

    private void cbAssignVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAssignVolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAssignVolActionPerformed

    private void cbDonationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonationIDActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbDonationIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestsAssign;
    private javax.swing.JButton btnRequestsSend;
    private javax.swing.JComboBox<String> cbAssignVol;
    private javax.swing.JComboBox<String> cbDonationID;
    private javax.swing.JLabel cbVolunteerLbl;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblDonationID;
    private javax.swing.JLabel lblFoodRequestsTitle;
    private javax.swing.JLabel lblFoodRequestsTitle1;
    private javax.swing.JLabel lblFoodRequestsid1;
    private javax.swing.JLabel lblRequestsid;
    private javax.swing.JTable tblAccessoryRequests;
    private javax.swing.JTextField txtRequestsid;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblAccessoryRequests.getModel();
        model.setRowCount(0);
        for (AccessoryRequestorder rq : ecosystem.getReqorderDirectory().getReqOrderList()) {
            if (rq.getReqPantryName().equals(FCPname)) {
                Object[] row = new Object[6];
                row[0] = rq;
                row[1] = rq.getReqName();
                row[2] = rq.getReqOrderQuant();
                row[3] = rq.getReqOrderType();
                row[4] = rq.getReqOrderStatus();
                if (rq.getReqDonId() != null) {
                    row[5] = rq.getReqDonId();

                } else {
                    row[5] = "-";
                }
                model.addRow(row);
            }
        }
    }
}
